package executor

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// GvisorExecutor runs commands inside gVisor sandboxes via `runsc run`.
// Each sandbox is one OCI bundle written to ~/.tofi/runs/{runID}/ with a
// config.json generated by BuildOCIConfig. The bundle is destroyed after the
// command returns.
type GvisorExecutor struct {
	homeDir  string // ~/.tofi
	runscBin string // path to the runsc binary
	uid      uint32 // uid the sandboxed process runs as
	gid      uint32
	stateDir string // runsc --root state directory
}

// NewGvisorExecutor builds an executor. runscBin must be an absolute path.
// Uses the current OS user's uid/gid for in-sandbox identity so that files
// created in bind-mounted user dirs stay owned by the real user.
func NewGvisorExecutor(homeDir, runscBin string) (*GvisorExecutor, error) {
	if homeDir == "" {
		return nil, fmt.Errorf("homeDir is required")
	}
	if runscBin == "" {
		return nil, fmt.Errorf("runscBin is required")
	}

	uid, gid := currentUIDGID()
	stateDir := filepath.Join(homeDir, "runsc-state")
	if err := os.MkdirAll(stateDir, 0700); err != nil {
		return nil, fmt.Errorf("create runsc state dir: %w", err)
	}
	return &GvisorExecutor{
		homeDir:  homeDir,
		runscBin: runscBin,
		uid:      uid,
		gid:      gid,
		stateDir: stateDir,
	}, nil
}

// CreateSandbox materialises the dir tree this run needs on the host.
// sandboxPath returned = ~/.tofi/runs/{CardID}.
func (g *GvisorExecutor) CreateSandbox(cfg SandboxConfig) (string, error) {
	if cfg.CardID == "" {
		return "", fmt.Errorf("CardID is required")
	}
	homeDir := cfg.HomeDir
	if homeDir == "" {
		homeDir = g.homeDir
	}

	pkgDir := filepath.Join(homeDir, "packages")
	for _, sub := range []string{
		"cache/pip", "cache/uv", "cache/npm",
		"wheels", "artifacts",
	} {
		if err := os.MkdirAll(filepath.Join(pkgDir, sub), 0755); err != nil {
			return "", fmt.Errorf("create packages dir %s: %w", sub, err)
		}
	}

	if cfg.UserID != "" {
		if err := ensurePersistentUserDirs(filepath.Join(homeDir, "users", cfg.UserID)); err != nil {
			return "", fmt.Errorf("create user dir: %w", err)
		}
	}

	runDir := filepath.Join(homeDir, "runs", cfg.CardID)
	for _, sub := range []string{"tmp", "overlay/local", "rootfs"} {
		if err := os.MkdirAll(filepath.Join(runDir, sub), 0755); err != nil {
			return "", fmt.Errorf("create run dir %s: %w", sub, err)
		}
	}
	if err := ensurePersistentUserDirs(filepath.Join(runDir, "overlay", "local")); err != nil {
		return "", fmt.Errorf("prepare ephemeral overlay: %w", err)
	}
	return runDir, nil
}

// Execute writes the OCI config.json, runs the sandbox via `runsc run`, and
// returns combined stdout/stderr. Install mode is picked from env
// TOFI_INSTALL_MODE (default persistent).
func (g *GvisorExecutor) Execute(ctx context.Context, sandboxPath, userDir, command string, timeoutSec int, env map[string]string) (string, error) {
	if sandboxPath == "" {
		return "", fmt.Errorf("sandboxPath is required")
	}
	if timeoutSec <= 0 {
		timeoutSec = 60
	}
	if timeoutSec > MaxTimeout {
		timeoutSec = MaxTimeout
	}

	homeDir := g.homeDir
	if homeDir == "" {
		homeDir = filepath.Dir(filepath.Dir(sandboxPath))
	}
	pkgDir := filepath.Join(homeDir, "packages")

	mode := InstallModePersistent
	if env["TOFI_INSTALL_MODE"] == string(InstallModeEphemeral) {
		mode = InstallModeEphemeral
	}

	if mode == InstallModePersistent && userDir == "" {
		return "", fmt.Errorf("persistent install mode requires userDir")
	}

	extraEnv := make([]string, 0, len(env))
	for k, v := range env {
		if k == "TOFI_INSTALL_MODE" {
			continue
		}
		extraEnv = append(extraEnv, k+"="+v)
	}

	spec, err := BuildOCIConfig(OCISpecOptions{
		Command:     command,
		UID:         g.uid,
		GID:         g.gid,
		RunDir:      sandboxPath,
		UserDir:     userDir,
		PkgDir:      pkgDir,
		InstallMode: mode,
		TimeoutSec:  timeoutSec,
		ExtraEnv:    extraEnv,
	})
	if err != nil {
		return "", fmt.Errorf("build OCI spec: %w", err)
	}
	configPath := filepath.Join(sandboxPath, "config.json")
	if err := os.WriteFile(configPath, spec, 0644); err != nil {
		return "", fmt.Errorf("write config.json: %w", err)
	}

	logAuditLine(sandboxPath, command)

	runCtx, cancel := context.WithTimeout(ctx, time.Duration(timeoutSec)*time.Second)
	defer cancel()

	containerID := filepath.Base(sandboxPath)
	// Flags required to run runsc as a non-root user under systemctl --user:
	//   --rootless       skips newuidmap/newgidmap; the process inside the
	//                    sandbox sees itself as root while staying mapped to
	//                    the real host UID outside. Required because our
	//                    subuid/subgid ranges aren't wired for multi-UID
	//                    containers.
	//   --ignore-cgroups runsc otherwise tries to create a sub-cgroup per
	//                    sandbox and hits EPERM on cgroup.subtree_control
	//                    without explicit delegation. Per-process rlimits
	//                    (NPROC/NOFILE/FSIZE/CPU) in the OCI spec stay in
	//                    effect — enough to bound one sandbox.
	cmd := exec.CommandContext(runCtx,
		g.runscBin,
		"--root", g.stateDir,
		"--network", "sandbox",
		"--rootless",
		"--ignore-cgroups",
		"run",
		"--bundle", sandboxPath,
		containerID,
	)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &limitedWriter{w: &stdout, limit: MaxOutputBytes}
	cmd.Stderr = &limitedWriter{w: &stderr, limit: MaxOutputBytes}

	log.Printf("🛡️  [gvisor] runsc run %s (%.80s…)", containerID, command)
	runErr := cmd.Run()

	output := stdout.String()
	if errOut := stderr.String(); errOut != "" {
		if output != "" {
			output += "\n"
		}
		output += errOut
	}

	if runCtx.Err() == context.DeadlineExceeded {
		g.forceDelete(containerID)
		return output, fmt.Errorf("command timed out after %d seconds", timeoutSec)
	}
	if runErr != nil {
		return output, fmt.Errorf("command failed: %v\n%s", runErr, output)
	}
	return strings.TrimRight(output, "\n"), nil
}

// Cleanup removes the run directory and any leftover runsc state.
func (g *GvisorExecutor) Cleanup(sandboxPath string) {
	if sandboxPath == "" {
		return
	}
	if !strings.Contains(sandboxPath, "/runs/") {
		return
	}
	containerID := filepath.Base(sandboxPath)
	g.forceDelete(containerID)
	_ = os.RemoveAll(sandboxPath)
}

func (g *GvisorExecutor) forceDelete(containerID string) {
	cmd := exec.Command(g.runscBin, "--root", g.stateDir, "delete", "--force", containerID)
	_ = cmd.Run()
}

// ensurePersistentUserDirs creates the full user/{uid} subtree expected by
// the OCI spec and the runtime shims.
func ensurePersistentUserDirs(root string) error {
	for _, sub := range []string{
		"bin",
		"config",
		"cache",
		"state/tool-runs",
		"python/venvs",
		"npm",
		"uv/tools",
		"artifacts",
	} {
		if err := os.MkdirAll(filepath.Join(root, sub), 0755); err != nil {
			return err
		}
	}
	return nil
}

// logAuditLine appends a timestamped record to sandboxPath/audit.log.
// Kept inside the ephemeral run dir — it is not a security audit log,
// just a debugging trail that disappears on teardown.
func logAuditLine(sandboxPath, command string) {
	f, err := os.OpenFile(filepath.Join(sandboxPath, "audit.log"),
		os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return
	}
	defer f.Close()
	fmt.Fprintf(f, "[%s] %s\n", time.Now().Format(time.RFC3339), command)
}

func currentUIDGID() (uint32, uint32) {
	u, err := user.Current()
	if err != nil {
		return 1000, 1000
	}
	uid, _ := strconv.ParseUint(u.Uid, 10, 32)
	gid, _ := strconv.ParseUint(u.Gid, 10, 32)
	return uint32(uid), uint32(gid)
}
